version: '3'

services:
    app:
        container_name: syu_clubs
        build:
            dockerfile: ./Dockerfile.dev
        ports:
            - 8000:8000
        environment: 
            - DJANGO_SETTINGS_MODULE=syu_clubs_api_server.settings.develop
        command:
            - bash
            - -c
            - |
                python manage.py migrate
                python manage.py runserver 0:8000