version: '3'

services:
    app:
        container_name: syu_clubs
        build:
            context: .
        restart: on-failure
        volumes:
            - ./:/app/
        environment: 
            - TZ=Asia/Seoul
        depends_on:
            - cloud-sql-proxy
        networks:
            syu_clubs:
                ipv4_address: 10.10.0.3

    cloud-sql-proxy:
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: /cloud_sql_proxy -instances=syu-clubs:asia-northeast3:syu-clubs-db=tcp:0.0.0.0:5000 -credential_file=app/config/secure/syuClubs-secure.json
        volumes: 
            - ./:/app/config
        ports: 
            - 5000:5000
        environment: 
            - TZ=Asia/Seoul
        networks:
            syu_clubs:
                ipv4_address: 10.10.0.2

networks:
    syu_clubs:
        driver: bridge
        ipam:
            config:
              - subnet: 10.10.0.0/16