version: '3'

services:
    app:
        container_name: syu_clubs
        build:
            dockerfile: ./Dockerfile
        expose:
            - 8000
        environment: 
            - DJANGO_SETTINGS_MODULE=syu_clubs_api_server.settings.prod
        command:
            - bash
            - -c
            - |
                python manage.py collectstatic
                python manage.py migrate
                gunicorn syu_clubs_api_server.wsgi:application --bind=0.0.0.0:8000

    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/app
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - syu_clubs


